In [ ]:
#Basics of Python

In [1]:
print("Hello World")

Hello World


In [2]:
print(5*6)

30


In [3]:
#this is comment

In [5]:
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [7]:
s=["windows","linux","mac"]
s

['windows', 'linux', 'mac']

In [8]:
x=[1,'hi',4.03]
x

[1, 'hi', 4.03]

In [9]:
t=("hi","hello","how are you")
t

('hi', 'hello', 'how are you')

In [11]:
t=('hi',4.0)
t

('hi', 4.0)

In [13]:
a=4
if a%2==0:
    print(1)
else:
    print(0)

1


In [15]:
i=1
while i<5:
    print(i)
    i=i+1

1
2
3
4


In [16]:
vegetables=['potato','cabbage','onion']
for x in vegetables:
    print(x)

potato
cabbage
onion


In [17]:
def myfunction(a):
    if a%2==0:
        return 1
    else:
        return 0
myfunction(5)

0

In [18]:
x=lambda a:a+1
print(x(5))

6


In [19]:
#Numpy Basics

In [20]:
import numpy as np

In [21]:
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [22]:
a[-1]

np.int64(4)

In [24]:
b=np.array([1,2,3,4,5,6,7,8,9])
b[0:9]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
c=b.copy()
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
d=b.view()
d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
b[6]=12
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
d

array([ 1,  2,  3,  4,  5,  6, 12,  8,  9])

In [29]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
b=a.reshape(4,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
c=np.array([13,14,15])
d=np.concatenate((a,c))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
np.array_split(d,2)

[array([1, 2, 3, 4, 5, 6, 7, 8]), array([ 9, 10, 11, 12, 13, 14, 15])]

In [41]:
np.where(d==4)

(array([3]),)

In [42]:
np.where(d%2==0)

(array([ 1,  3,  5,  7,  9, 11, 13]),)

In [43]:
c=np.array([3,4,2,10,5])
np.sort(c)

array([ 2,  3,  4,  5, 10])

In [44]:
c=np.array([[2,3,1,5],[5,1,2,4]])
np.sort(c)

array([[1, 2, 3, 5],
       [1, 2, 4, 5]])

In [45]:
c=np.array(['apple','orange','banana','mango'])
np.sort(c)

array(['apple', 'banana', 'mango', 'orange'], dtype='<U6')

In [46]:
np.random.randint(100)

22

In [48]:
np.random.rand(10)

array([0.87289044, 0.49389449, 0.01623566, 0.13598313, 0.47829253,
       0.19180128, 0.38908095, 0.7925124 , 0.522935  , 0.50229161])

In [49]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [50]:
np.ones(2)

array([1., 1.])

In [51]:
#Panda Basics

In [52]:
import numpy as np
import pandas as pd

In [53]:
dic1={
    "name":['rohan','seema','mahesh','shruti'],
    "marks":[9,55,67,98],
    "city":['Delhi','Jaipur','Rampur','Barilly']
}

In [54]:
df=pd.DataFrame(dic1)

In [55]:
df

name  marks     city
0   rohan      9    Delhi
1   seema     55   Jaipur
2  mahesh     67   Rampur
3  shruti     98  Barilly

In [57]:
df.index=[1,2,3,4]

In [58]:
df

name  marks     city
1   rohan      9    Delhi
2   seema     55   Jaipur
3  mahesh     67   Rampur
4  shruti     98  Barilly

In [59]:
ser=pd.Series(np.random.rand(20))
ser

0     0.004614
1     0.927907
2     0.474816
3     0.255655
4     0.565767
5     0.764705
6     0.632539
7     0.237589
8     0.301721
9     0.391843
10    0.160798
11    0.535298
12    0.194503
13    0.220850
14    0.493815
15    0.771809
16    0.500173
17    0.406409
18    0.323309
19    0.083264
dtype: float64

In [60]:
type(ser)

pandas.core.series.Series

In [62]:
newdf=pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [63]:
newdf

0         1         2         3         4
0    0.433174  0.876117  0.517518  0.676371  0.051198
1    0.808642  0.574713  0.621850  0.296627  0.889921
2    0.972093  0.862305  0.185767  0.420970  0.368922
3    0.255399  0.435936  0.360749  0.834497  0.901796
4    0.117763  0.116533  0.643665  0.041439  0.214610
..        ...       ...       ...       ...       ...
329  0.606099  0.649082  0.740178  0.352859  0.924053
330  0.868915  0.039399  0.818450  0.882504  0.201175
331  0.937144  0.610560  0.646106  0.947146  0.207415
332  0.527172  0.437952  0.597648  0.492257  0.467256
333  0.889787  0.130349  0.163789  0.113256  0.717820

[334 rows x 5 columns]

In [64]:
newdf.head(3)

0         1         2         3         4
0  0.433174  0.876117  0.517518  0.676371  0.051198
1  0.808642  0.574713  0.621850  0.296627  0.889921
2  0.972093  0.862305  0.185767  0.420970  0.368922

In [65]:
newdf.tail(3)

0         1         2         3         4
331  0.937144  0.610560  0.646106  0.947146  0.207415
332  0.527172  0.437952  0.597648  0.492257  0.467256
333  0.889787  0.130349  0.163789  0.113256  0.717820

In [66]:
newdf.sort_index(axis=0)

0         1         2         3         4
0    0.433174  0.876117  0.517518  0.676371  0.051198
1    0.808642  0.574713  0.621850  0.296627  0.889921
2    0.972093  0.862305  0.185767  0.420970  0.368922
3    0.255399  0.435936  0.360749  0.834497  0.901796
4    0.117763  0.116533  0.643665  0.041439  0.214610
..        ...       ...       ...       ...       ...
329  0.606099  0.649082  0.740178  0.352859  0.924053
330  0.868915  0.039399  0.818450  0.882504  0.201175
331  0.937144  0.610560  0.646106  0.947146  0.207415
332  0.527172  0.437952  0.597648  0.492257  0.467256
333  0.889787  0.130349  0.163789  0.113256  0.717820

[334 rows x 5 columns]

In [67]:
newdf.drop(0,axis=1)

1         2         3         4
0    0.876117  0.517518  0.676371  0.051198
1    0.574713  0.621850  0.296627  0.889921
2    0.862305  0.185767  0.420970  0.368922
3    0.435936  0.360749  0.834497  0.901796
4    0.116533  0.643665  0.041439  0.214610
..        ...       ...       ...       ...
329  0.649082  0.740178  0.352859  0.924053
330  0.039399  0.818450  0.882504  0.201175
331  0.610560  0.646106  0.947146  0.207415
332  0.437952  0.597648  0.492257  0.467256
333  0.130349  0.163789  0.113256  0.717820

[334 rows x 4 columns]

In [68]:
newdf.dropna(inplace=True)